syntax = "proto3";

option csharp_namespace = "MarketBasketAnalysisStorage.Contracts.V1";

package market_basket_analysis_storage.contracts.v1;

import "google/protobuf/timestamp.proto";

service AssociationRuleSetStorage {
  rpc Get(GetRequest) returns (GetResponse);
  rpc Load(LoadRequest) returns (stream LoadResponse);
  rpc StartSave(StartSaveRequest) returns (StartSaveResponse);
  rpc SaveItemChunk(SaveItemChunkRequest) returns (SaveItemChunkResponse);
  rpc SaveAssociationRuleChunk(SaveAssociationRuleChunkRequest) returns (SaveAssociationRuleChunkResponse);
  rpc CompleteSave(CompleteSaveRequest) returns (CompleteSaveResponse);
  rpc Remove(RemoveRequest) returns (RemoveResponse);
}

message GetRequest {}

message GetResponse {
  repeated AssociationRuleSet sets = 1;
}

message LoadRequest {
  int32 set_id = 1;
}

message LoadResponse {
  AssociationRuleSetPart part = 1;
}

message StartSaveRequest {
  message AssociationRuleSet {
    string name = 1;
    optional string description = 2;
    int32 transactions_count = 3;
  }
  AssociationRuleSet set = 1;
}

message StartSaveResponse {
  int32 set_id = 1;
}

message SaveItemChunkRequest {
  int32 set_id = 1;
  ItemChunk chunk = 2;
}

message SaveItemChunkResponse {}

message SaveAssociationRuleChunkRequest {
  int32 set_id = 1;
  AssociationRuleChunk chunk = 2;
}

message SaveAssociationRuleChunkResponse {}

message CompleteSaveRequest {
  int32 set_id = 1;
}

message CompleteSaveResponse {}

message RemoveRequest {
  int32 set_id = 1;
}

message RemoveResponse {}

message AssociationRuleSetPart {
  oneof payload {
    AssociationRuleSet set = 1;
    ItemChunk item_chunk = 2;
    AssociationRuleChunk association_rule_chunk = 3;
  }
}

message AssociationRuleSet {
  int32 id = 1;
  string name = 2;
  string description = 3;
  int32 transactions_count = 4;
  google.protobuf.Timestamp created_at = 5;
}

message ItemChunk {
  repeated Item items = 1;
}

message AssociationRuleChunk {
  repeated AssociationRule association_rules = 1;
}

message Item {
  int32 id = 1;
  string name = 2;
  bool is_group = 3;
  int32 count = 4;
}

message AssociationRule {
  int32 left_hand_side_id = 1;
  int32 right_hand_side_id = 2;
  int32 count = 3;
}
