// <auto-generated />
using MarketBasketAnalysisStorage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketBasketAnalysis.Server.Data.Migrations
{
    [DbContext(typeof(MarketBasketAnalysisDbContext))]
    partial class MarketBasketAnalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketBasketAnalysisStorage.Data.AssociationRuleChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationRuleSetId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.HasKey("Id");

                    b.HasIndex("AssociationRuleSetId");

                    b.ToTable("AssociationRuleChunks");
                });

            modelBuilder.Entity("MarketBasketAnalysisStorage.Data.AssociationRuleSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TransactionCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AssociationRuleSets");
                });

            modelBuilder.Entity("MarketBasketAnalysisStorage.Data.AssociationRuleSetMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationRuleSetId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastItemChunkIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("LastRuleChunkIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("LastSavedItemChunkIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("LastSavedRuleChunkIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssociationRuleSetId");

                    b.ToTable("AssociationRuleSetMetadatas");
                });

            modelBuilder.Entity("MarketBasketAnalysisStorage.Data.ItemChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationRuleSetId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.HasKey("Id");

                    b.HasIndex("AssociationRuleSetId");

                    b.ToTable("ItemChunks");
                });

            modelBuilder.Entity("MarketBasketAnalysisStorage.Data.AssociationRuleChunk", b =>
                {
                    b.HasOne("MarketBasketAnalysisStorage.Data.AssociationRuleSet", "AssociationRuleSet")
                        .WithMany()
                        .HasForeignKey("AssociationRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociationRuleSet");
                });

            modelBuilder.Entity("MarketBasketAnalysisStorage.Data.AssociationRuleSetMetadata", b =>
                {
                    b.HasOne("MarketBasketAnalysisStorage.Data.AssociationRuleSet", "AssociationRuleSet")
                        .WithMany()
                        .HasForeignKey("AssociationRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociationRuleSet");
                });

            modelBuilder.Entity("MarketBasketAnalysisStorage.Data.ItemChunk", b =>
                {
                    b.HasOne("MarketBasketAnalysisStorage.Data.AssociationRuleSet", "AssociationRuleSet")
                        .WithMany()
                        .HasForeignKey("AssociationRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociationRuleSet");
                });
#pragma warning restore 612, 618
        }
    }
}
